### ISSUE TITLE
Missing GET support

### ISSUE THREAD

**Issue by jypma** [bluelabsio/s3-stream#5]
@joearasin Are you accepting pull requests for this? I'd like to add simple GET support for S3 keys.

**Comment by joearasin** [comment]
Yep!

**Comment by joearasin** [comment]
Would the API for such be retrieving an S3 Key as a Source[Bytestring]?

**Comment by jypma** [comment]
Yupp. Shouldn't be too big a deal; sign the request, expose akka-http's resulting `Source[ByteString]` pretty much directly.

I'll try to get sth up on Monday.

**Comment by joearasin** [comment]
Thanks @jypma -- Sorry about taking so long.
